### PR TITLE
Reintroduce missing features after cleanup + Channel exclusion.

### PR DESCRIPTION
**Pull request by dongle-the-gadget**
- GitHub button (previous).
- Guild exclusion (previous).
- Channel exclusion (messages in excluded channels will not be credited towards message count and XP).

### CODE REVIEW

**Comment by dongle-the-gadget** [comment]
Expanded scope to include bugfixes.

**Comment by SapphireDisD** [comment]
Sorry for the really late response, but I'm about to merge!

**Comment by dongle-the-gadget** [comment]
No problem, I think I’ve dealt with even later responses.

**Comment by dongle-the-gadget** [comment]
And a fact btw: I accidentally leaked the bot token I used for testing - Discord automatically reset it tho.

**Pull request merged**
